Improve Debian Packages
crabnebula-dev/cargo-packager pull request #126
Opened 2024-01-09 19:01 UTC by naman-crabnebula

I am adding some necessary `config` options for debian packages.

These should be accessible via `[package.metadata.packager.deb]`

These changes are running perfectly fine on Arch Linux as well as Debian, but please, review carefully before approving.

Also, this is not complete yet, I will be adding certain options as well.

2024-01-09 23:50 UTC, amr-crabnebula requested changes
just missing a change file

2024-01-10 09:12 UTC, naman-crabnebula commented
> just missing a change file

Yeah, it is not complete yet.

2024-01-10 16:03 UTC, lucasfernog-crabnebula reviewed
Nice job, as long as we add the change file!

2024-01-15 15:18 UTC, amr-crabnebula commented on .changes/priority-and-section.md
> +Add the support for priority and section in Debian Config
```suggestion
Add `priority` and `section` options in Debian config
```

2024-01-15 15:25 UTC, amr-crabnebula commented on .changes/priority-and-section.md
> +"cargo-packager": minor
```suggestion
"cargo-packager": patch
"@crabnebula/packager": patch
```

2024-01-15 15:25 UTC, amr-crabnebula approved these changes

2024-01-15 15:27 UTC, amr-crabnebula commented on crates/packager/src/config/mod.rs
> +    }
```suggestion
    pub fn section<S: Into<String>>(mut self, section: S) -> Self {
        self.section.replace(section.into());
        self
    }

    /// Change the priority of the Debian Package. By default, it is set to `optional`.
    /// Recognized Priorities as of now are :  `required`, `important`, `standard`, `optional`, `extra`
    pub fn priority<S: Into<String>>(mut self, priority: S) -> Self {
        self.priority.replace(priority.into());
        self
    }
```

2024-01-15 15:27 UTC, amr-crabnebula approved these changes

2024-01-15 16:16 UTC, merged