fix(pacman): enclose directory paths in `PKGBUILD` in double quotes
crabnebula-dev/cargo-packager pull request #264
Opened 2024-08-21 23:33 UTC by kevinaboos

This ensures that paths with spaces on the target machine are properly preserved during pacman's installation of the package.

Context: some users of our Moxin app that was packaged for Arch Linux using `cargo-packager` reported that their pacman install command was failing due to paths containing whitespace.
Thanks to @cassaundra for proposing this fix and confirming that it works.

2024-08-22 13:39 UTC, amr-crabnebula requested changes
Thank you, could you add a change file in `.changes` directory?

something like this:
```md
---
"cargo-packager": patch
"@crabnebula/packager": patch
---

Fix `pacman` package failing to install when source directory contained whitespace.
```

2024-10-09 20:00 UTC, lucasfernog-crabnebula commented
I tried pushing the change file myself but I couldn't 😢 lacking permissions on your repo

2024-10-09 22:02 UTC, kevinaboos commented
oh shoot, sorry guys I completely forgot about this PR in the hecticness of so much travel. Will push shortly!

2024-10-09 22:04 UTC, kevinaboos commented
done! thanks for the reminder, and my apologies for the delay.

2024-10-10 05:11 UTC, amr-crabnebula approved these changes

2024-10-10 06:12 UTC, denjell-crabnebula approved these changes
Normally we require that commits are signed, but in the interest of approving your contribution I will relax the requirements this time.

2024-10-10 06:20 UTC, kevinaboos commented
> Normally we require that commits are signed, but in the interest of approving your contribution I will relax the requirements this time.

thanks, will keep that in mind for my next contribution.

2024-10-10 07:19 UTC, merged